### ISSUE TITLE
Gif To Png

### ISSUE THREAD

**Issue by wenjvQAQ** [Tichau/FileConverter#162] opened 2021-04-14 13:23 UTC
# Tichau

can you code GIf to Png???

PLEASE!!!!

**Comment by BillyBobJones678** [comment] 2021-06-04 00:30
use this while your waiting https://convertio.co/gif-png/

**Comment by eadmaster** [comment] 2023-04-07 20:29
duplicate of https://github.com/Tichau/FileConverter/issues/115

**Closed** 2024-01-19 16:46 UTC
Labels: duplicate
